### ISSUE TITLE
Buttons/Hover

### ISSUE THREAD

**Issue by moqy** [iamjonasmarlo/MOQY#11]
Haben die Buttons schon die entsprechende Laufweite?
Und geht das beim Hovern mit der Laufweitenreduzierung?

Ansonsten ist das mit der Farbänderung beim Hovern auch gar nicht schlecht (vllt kann man auch beides kombinieren). Frage hier: Geht das dass sich der Button in der entsprechenden Konturfarbe füllt und die Schrift dann Transparent wird sodass der Hintergrund durchscheint? Falls nicht dann einfach die Schrift immer weiß beim Hovern

**Comment by iamjonasmarlo** [comment]
Leider klappt beides nicht. Das Problem ist, dass die Schrift einen Abstand x nach links/rechts und y nach oben/unten hat. Wenn sie nun die Laufweite bei einem hover verringert, dann wird damit der ganze Button schmaler und verändert sich in der Breite. Das sieht komisch aus, deswegen habe ich es raus gelassen. Ich kann es aber auch gerne mal reinpacken, dann siehst du was ich meine.

**Comment by iamjonasmarlo** [comment]
Ach ja, zur Schriftfarbe der Buttons: Leider kann man via HTML/CSS keinen transparenten Text erstellen :(
