### ISSUE TITLE
Laufweiten

### ISSUE THREAD

**Issue by moqy** [iamjonasmarlo/MOQY#2]
Habe die Laufweiten aller Menüpunkte (obere + untere) auf 50 in Indesign, weiß nicht was das Code-Equivalent dafür ist aber kannst du eine entsprechende Laufweite dafür einstellen? 
Die Laufweite bleibt überall gleich, auch in allen Texten. 
Buttons haben die doppelte Laufweite. Kann man bei den Buttons beim Hovern die Laufweite halbieren?

**Comment by iamjonasmarlo** [comment]
Laufweite habe ich global angepasst.

Die Laufweite lässt sich beim hover halbieren. Baue ich ein :)

**Comment by moqy** [comment]
Perfekt! Perfekte Menü-Hover-Animation btw!
